# Copyright © 2019-2023
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI

on: [push, pull_request]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        name: [regression, opencl]
        os: [ubuntu-20.04, centos-7]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo bash ./ci/system_updates.sh

      - name: Setup Toolchain
        run: |
          TOOLDIR=$PWD/tools
          mkdir -p build
          cd build
          ../configure --tooldir=$TOOLDIR
          ci/toolchain_install.sh --all

      - name: Setup Third Party
        run: |
          make -C third_party > /dev/null

      - name: Run Build
        run: |
          TOOLDIR=$PWD/tools
          mkdir -p build64
          cd build64
          ../configure --tooldir=$TOOLDIR --xlen=64
          source ci/toolchain_env.sh
          make software -s > /dev/null
          make tests -s > /dev/null

      - name: Run tests
        run: |
          cd build64
          source ci/toolchain_env.sh
          chmod -R +x . # Ensure all files have executable permissions
          if [ "${{ matrix.name }}" == "regression" ]; then
            ./ci/regression.sh --unittest
            ./ci/regression.sh --isa
            ./ci/regression.sh --kernel
            ./ci/regression.sh --synthesis
            ./ci/regression.sh --regression
          else
            ./ci/regression.sh --${{ matrix.name }}
          fi